<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Results &amp; Conclusions – Flight Diversions Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-a6e161b2431e1f94a14e0f5d32135a3c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4a17e18fdf56099d4f6da1e105f33a53.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-a6e161b2431e1f94a14e0f5d32135a3c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1b17e506d66c28969ad50ead2b15a1df.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4d826d7a8f3217ef8273c677342d8834.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-1b17e506d66c28969ad50ead2b15a1df.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" defer="" src="https://buttons.github.io/buttons.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Flight Diversions Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-collection.html"> 
<span class="menu-text">Data Collection</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-analysis.html"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-visualization.html"> 
<span class="menu-text">Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04-results.html"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05-dashboard.html"> 
<span class="menu-text">Dashboard</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-results.html">Results &amp; Conclusions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Collection &amp; Preparation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis Methodology</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Results &amp; Conclusions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings"><span class="header-section-number">2</span> Key Findings</a>
  <ul class="collapse">
  <li><a href="#finding-1-american-airlines-shows-significantly-higher-diversion-rates-than-competitors" id="toc-finding-1-american-airlines-shows-significantly-higher-diversion-rates-than-competitors" class="nav-link" data-scroll-target="#finding-1-american-airlines-shows-significantly-higher-diversion-rates-than-competitors"><span class="header-section-number">2.1</span> Finding 1: American Airlines Shows Significantly Higher Diversion Rates Than Competitors</a></li>
  <li><a href="#finding-2-regional-vs.-system-wide-disruptions-require-different-operational-responses" id="toc-finding-2-regional-vs.-system-wide-disruptions-require-different-operational-responses" class="nav-link" data-scroll-target="#finding-2-regional-vs.-system-wide-disruptions-require-different-operational-responses"><span class="header-section-number">2.2</span> Finding 2: Regional vs.&nbsp;System-Wide Disruptions Require Different Operational Responses</a></li>
  <li><a href="#finding-3-diversion-hub-airports-show-consistent-geographic-patterns" id="toc-finding-3-diversion-hub-airports-show-consistent-geographic-patterns" class="nav-link" data-scroll-target="#finding-3-diversion-hub-airports-show-consistent-geographic-patterns"><span class="header-section-number">2.3</span> Finding 3: Diversion Hub Airports Show Consistent Geographic Patterns</a></li>
  </ul></li>
  <li><a href="#quantitative-summary" id="toc-quantitative-summary" class="nav-link" data-scroll-target="#quantitative-summary"><span class="header-section-number">3</span> Quantitative Summary</a></li>
  <li><a href="#cluster-summary" id="toc-cluster-summary" class="nav-link" data-scroll-target="#cluster-summary"><span class="header-section-number">4</span> Cluster Summary</a>
  <ul class="collapse">
  <li><a href="#cluster-1-san-diego-san---system-wide-disruption" id="toc-cluster-1-san-diego-san---system-wide-disruption" class="nav-link" data-scroll-target="#cluster-1-san-diego-san---system-wide-disruption"><span class="header-section-number">4.1</span> Cluster 1: San Diego (SAN) - System-Wide Disruption</a></li>
  <li><a href="#cluster-2-dallasfort-worth-dfw---regional-disruption" id="toc-cluster-2-dallasfort-worth-dfw---regional-disruption" class="nav-link" data-scroll-target="#cluster-2-dallasfort-worth-dfw---regional-disruption"><span class="header-section-number">4.2</span> Cluster 2: Dallas/Fort Worth (DFW) - Regional Disruption</a></li>
  <li><a href="#cluster-3-chicago-ohare-ord---regional-disruption" id="toc-cluster-3-chicago-ohare-ord---regional-disruption" class="nav-link" data-scroll-target="#cluster-3-chicago-ohare-ord---regional-disruption"><span class="header-section-number">4.3</span> Cluster 3: Chicago O’Hare (ORD) - Regional Disruption</a></li>
  </ul></li>
  <li><a href="#operational-implications" id="toc-operational-implications" class="nav-link" data-scroll-target="#operational-implications"><span class="header-section-number">5</span> Operational Implications</a>
  <ul class="collapse">
  <li><a href="#for-airlines" id="toc-for-airlines" class="nav-link" data-scroll-target="#for-airlines"><span class="header-section-number">5.1</span> For Airlines</a></li>
  <li><a href="#for-airport-operations" id="toc-for-airport-operations" class="nav-link" data-scroll-target="#for-airport-operations"><span class="header-section-number">5.2</span> For Airport Operations</a></li>
  <li><a href="#for-policy-makers" id="toc-for-policy-makers" class="nav-link" data-scroll-target="#for-policy-makers"><span class="header-section-number">5.3</span> For Policy Makers</a></li>
  </ul></li>
  <li><a href="#statistical-confidence" id="toc-statistical-confidence" class="nav-link" data-scroll-target="#statistical-confidence"><span class="header-section-number">6</span> Statistical Confidence</a>
  <ul class="collapse">
  <li><a href="#methodology-validation" id="toc-methodology-validation" class="nav-link" data-scroll-target="#methodology-validation"><span class="header-section-number">6.1</span> Methodology Validation</a></li>
  <li><a href="#can-we-generalize-these-findings" id="toc-can-we-generalize-these-findings" class="nav-link" data-scroll-target="#can-we-generalize-these-findings"><span class="header-section-number">6.2</span> Can We Generalize These Findings?</a></li>
  </ul></li>
  <li><a href="#what-surprised-us" id="toc-what-surprised-us" class="nav-link" data-scroll-target="#what-surprised-us"><span class="header-section-number">7</span> What Surprised Us</a></li>
  <li><a href="#what-this-reveals-about-aviation" id="toc-what-this-reveals-about-aviation" class="nav-link" data-scroll-target="#what-this-reveals-about-aviation"><span class="header-section-number">8</span> What This Reveals About Aviation</a>
  <ul class="collapse">
  <li><a href="#the-bigger-picture" id="toc-the-bigger-picture" class="nav-link" data-scroll-target="#the-bigger-picture"><span class="header-section-number">8.1</span> The Bigger Picture</a></li>
  <li><a href="#system-resilience" id="toc-system-resilience" class="nav-link" data-scroll-target="#system-resilience"><span class="header-section-number">8.2</span> System Resilience</a></li>
  <li><a href="#passenger-experience-implications" id="toc-passenger-experience-implications" class="nav-link" data-scroll-target="#passenger-experience-implications"><span class="header-section-number">8.3</span> Passenger Experience Implications</a></li>
  </ul></li>
  <li><a href="#limitations-of-this-analysis" id="toc-limitations-of-this-analysis" class="nav-link" data-scroll-target="#limitations-of-this-analysis"><span class="header-section-number">9</span> Limitations of This Analysis</a>
  <ul class="collapse">
  <li><a href="#data-limitations" id="toc-data-limitations" class="nav-link" data-scroll-target="#data-limitations"><span class="header-section-number">9.1</span> Data Limitations</a></li>
  <li><a href="#methodological-limitations" id="toc-methodological-limitations" class="nav-link" data-scroll-target="#methodological-limitations"><span class="header-section-number">9.2</span> Methodological Limitations</a></li>
  </ul></li>
  <li><a href="#future-research-directions" id="toc-future-research-directions" class="nav-link" data-scroll-target="#future-research-directions"><span class="header-section-number">10</span> Future Research Directions</a>
  <ul class="collapse">
  <li><a href="#short-term-easy-to-do" id="toc-short-term-easy-to-do" class="nav-link" data-scroll-target="#short-term-easy-to-do"><span class="header-section-number">10.1</span> Short Term (Easy to Do)</a></li>
  <li><a href="#medium-term-more-work" id="toc-medium-term-more-work" class="nav-link" data-scroll-target="#medium-term-more-work"><span class="header-section-number">10.2</span> Medium Term (More Work)</a></li>
  </ul></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">11</span> Reproducibility</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">12</span> Conclusion</a></li>
  <li><a href="#about-this-analysis" id="toc-about-this-analysis" class="nav-link" data-scroll-target="#about-this-analysis"><span class="header-section-number">13</span> About This Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Results &amp; Conclusions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">1</span> Executive Summary</h2>
<p>This analysis examined 64,815 flight diversions across the United States from July 2021 to December 2024, identifying 3 distinct diversion clusters and uncovering patterns in when, where, and how flights are redirected from their intended destinations.</p>
<p><strong>Main Finding</strong>: Flight diversions are not random; they cluster around specific hub airports during specific time periods, suggesting systematic operational vulnerabilities in the U.S. aviation system.</p>
<hr>
</section>
<section id="key-findings" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="key-findings"><span class="header-section-number">2</span> Key Findings</h2>
<section id="finding-1-american-airlines-shows-significantly-higher-diversion-rates-than-competitors" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="finding-1-american-airlines-shows-significantly-higher-diversion-rates-than-competitors"><span class="header-section-number">2.1</span> Finding 1: American Airlines Shows Significantly Higher Diversion Rates Than Competitors</h3>
<p><strong>The Discovery</strong>: American Airlines (AA) accounts for 27.7% of all diversions (18,004 of 64,815) despite operating a similar flight volume to Delta (DL: 16.8%, 10,886 diversions) and United (UA: 21.4%, 13,921 diversions). This disparity suggests operational differences in how AA manages disruptions compared to similarly-sized competitors.</p>
<p><strong>Evidence</strong>: - American Airlines: 18,004 diversions (27.7% of total) - United Airlines: 13,921 diversions (21.4%) - Delta Air Lines: 10,886 diversions (16.8%) - AA diverts 29% more frequently than DL despite similar fleet sizes</p>
<p><strong>Why It Matters</strong>: Higher diversion rates indicate either: (1) more aggressive scheduling in challenging conditions, (2) less efficient operational recovery procedures, or (3) different network design vulnerabilities. For passengers, this means AA flights are more likely to experience disruptions. For AA, this represents a competitive disadvantage and cost burden.</p>
<p><strong>Related Pattern</strong>: AA appears prominently in all three cluster periods (SAN, DFW, ORD), suggesting systemic rather than isolated issues across their network.</p>
<hr>
</section>
<section id="finding-2-regional-vs.-system-wide-disruptions-require-different-operational-responses" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="finding-2-regional-vs.-system-wide-disruptions-require-different-operational-responses"><span class="header-section-number">2.2</span> Finding 2: Regional vs.&nbsp;System-Wide Disruptions Require Different Operational Responses</h3>
<p><strong>The Discovery</strong>: Diversion clusters fall into two categories: regional events (where 50-60% of diversions go to the primary airport) and system-wide cascades (where only 48% go to primary, with remainder spreading across 60+ destinations). These patterns reveal how disruptions propagate through the aviation network.</p>
<p><strong>Evidence</strong>: - <strong>System-wide event (SAN)</strong>: Only 48.3% to primary, 290 total diversions across 60 destinations - <strong>Regional events (DFW, ORD)</strong>: 57-59% to primary, concentrated in regional airports (Texas hub, Midwest corridor) - System-wide events generate 50-100% more total diversions than regional ones - Arrival delays average 278.8 minutes, suggesting significant cascade effects</p>
<p><strong>Visualizations</strong>:</p>
<section id="san-diego-san---individual-cluster-map" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="san-diego-san---individual-cluster-map"><span class="header-section-number">2.2.1</span> San Diego (SAN) - Individual Cluster Map</h4>
<p><img src="cascade_cluster_1_SAN.png" class="img-fluid" alt="SAN Individual Cluster"> <em>Shows 140 diversions specifically to SAN, with origins concentrated on West Coast and Phoenix Sky Harbor (PHX) as primary diversion airport</em></p>
</section>
<section id="san-diego-san---system-wide-context" class="level4" data-number="2.2.2">
<h4 data-number="2.2.2" class="anchored" data-anchor-id="san-diego-san---system-wide-context"><span class="header-section-number">2.2.2</span> San Diego (SAN) - System-Wide Context</h4>
<p><img src="system_wide_cluster_1_SAN.png" class="img-fluid" alt="SAN System-Wide Map"> <em>Reveals the broader impact: 290 total diversions across 60 destinations, showing how a single airport disruption cascades throughout the entire system</em></p>
</section>
<section id="dallasfort-worth-dfw---individual-cluster-map" class="level4" data-number="2.2.3">
<h4 data-number="2.2.3" class="anchored" data-anchor-id="dallasfort-worth-dfw---individual-cluster-map"><span class="header-section-number">2.2.3</span> Dallas/Fort Worth (DFW) - Individual Cluster Map</h4>
<p><img src="cascade_cluster_2_DFW.png" class="img-fluid" alt="DFW Individual Cluster"> <em>Shows 110 diversions to DFW during Nov 4-5, 2024, with Houston (IAH) as primary alternate and origins spanning the country</em></p>
</section>
<section id="dallasfort-worth-dfw---system-wide-context" class="level4" data-number="2.2.4">
<h4 data-number="2.2.4" class="anchored" data-anchor-id="dallasfort-worth-dfw---system-wide-context"><span class="header-section-number">2.2.4</span> Dallas/Fort Worth (DFW) - System-Wide Context</h4>
<p><img src="system_wide_cluster_2_DFW.png" class="img-fluid" alt="DFW System-Wide Map"> <em>Demonstrates regional concentration: 186 total diversions stay concentrated in Texas/South-Central region, unlike the SAN system-wide cascade</em></p>
</section>
<section id="chicago-ohare-ord---individual-cluster-map" class="level4" data-number="2.2.5">
<h4 data-number="2.2.5" class="anchored" data-anchor-id="chicago-ohare-ord---individual-cluster-map"><span class="header-section-number">2.2.5</span> Chicago O’Hare (ORD) - Individual Cluster Map</h4>
<p><img src="cascade_cluster_3_ORD.png" class="img-fluid" alt="ORD Individual Cluster"> <em>Shows 108 diversions to ORD during Aug 24-26, 2021, with Indianapolis (IND) as primary alternate and Midwest corridor absorption</em></p>
</section>
<section id="chicago-ohare-ord---system-wide-context" class="level4" data-number="2.2.6">
<h4 data-number="2.2.6" class="anchored" data-anchor-id="chicago-ohare-ord---system-wide-context"><span class="header-section-number">2.2.6</span> Chicago O’Hare (ORD) - System-Wide Context</h4>
<p><img src="system_wide_cluster_3_ORD.png" class="img-fluid" alt="ORD System-Wide Map"> <em>Reveals regional pattern: 187 total diversions concentrated in Midwest, showing Midwest corridor coordination similar to Texas pattern</em></p>
<p><strong>Why It Matters</strong>: System-wide disruptions require network-wide coordination; regional events can be handled locally. Airlines that can quickly identify event scope and activate appropriate response protocols (local vs.&nbsp;system-wide) minimize passenger impact and operational costs.</p>
<p><strong>Related Pattern</strong>: SAN December 2024 event (system-wide) affected airlines’ operations across coasts; DFW and ORD events (regional) stayed concentrated in their geographic areas, allowing more localized recovery.</p>
<hr>
</section>
</section>
<section id="finding-3-diversion-hub-airports-show-consistent-geographic-patterns" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="finding-3-diversion-hub-airports-show-consistent-geographic-patterns"><span class="header-section-number">2.3</span> Finding 3: Diversion Hub Airports Show Consistent Geographic Patterns</h3>
<p><strong>The Discovery</strong>: The same airports repeatedly appear as primary diversion destinations (DEN, IAD, LAX, DFW, AUS) regardless of event type or airline, indicating they serve as the natural “safety valves” for the U.S. aviation system.</p>
<p><strong>Evidence</strong>: - Top 3 diversion airports: DEN (1,935), IAD (1,680), LAX (1,608) - These airports account for significant portion of all diversions - West Coast, Texas, and major hub cities consistently serve as overflow capacity - Same airports appear in all three cluster visualizations</p>
<p><strong>Why It Matters</strong>: Airlines can pre-position crews, aircraft, and ground services at these hub airports to handle predictable diversions. Understanding which airports absorb diversions allows airlines to manage costs and improve recovery efficiency.</p>
<p><strong>Related Pattern</strong>: DFW cluster shows Texas airports (IAH, DFW, SAT, AUS) work together; ORD cluster shows Midwest corridor (IND, STL, MKE) handles overflow—airlines can leverage regional networks for better recovery planning.</p>
<hr>
</section>
</section>
<section id="quantitative-summary" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="quantitative-summary"><span class="header-section-number">3</span> Quantitative Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 53%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Total Diversions Analyzed</strong></td>
<td>64,815</td>
</tr>
<tr class="even">
<td><strong>Time Period</strong></td>
<td>July 2021 - December 2024</td>
</tr>
<tr class="odd">
<td><strong>Diversion Clusters Identified</strong></td>
<td>3 major clusters</td>
</tr>
<tr class="even">
<td><strong>Unique Airports Involved</strong></td>
<td>377 diversion airports, 373 destination airports</td>
</tr>
<tr class="odd">
<td><strong>Airlines in Dataset</strong></td>
<td>10 airlines</td>
</tr>
<tr class="even">
<td><strong>Average Daily Diversions</strong></td>
<td>50.6</td>
</tr>
<tr class="odd">
<td><strong>Most Common Diversion Airports</strong></td>
<td>DEN (1,935), IAD (1,680), LAX (1,608)</td>
</tr>
<tr class="even">
<td><strong>Average Departure Delay (Diverted)</strong></td>
<td>32.2 minutes</td>
</tr>
<tr class="odd">
<td><strong>Average Arrival Delay (Diverted)</strong></td>
<td>278.8 minutes</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="cluster-summary" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="cluster-summary"><span class="header-section-number">4</span> Cluster Summary</h2>
<section id="cluster-1-san-diego-san---system-wide-disruption" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="cluster-1-san-diego-san---system-wide-disruption"><span class="header-section-number">4.1</span> Cluster 1: San Diego (SAN) - System-Wide Disruption</h3>
<ul>
<li><strong>Primary Destination</strong>: SAN (San Diego International)</li>
<li><strong>Common Diversion</strong>: PHX (Phoenix Sky Harbor)</li>
<li><strong>Period</strong>: December 18-21, 2024</li>
<li><strong>Number of Events</strong>: 140 diversions to SAN; 290 system-wide</li>
<li><strong>Unique Origins</strong>: 43 airports (ATL, SFO, DEN most common)</li>
<li><strong>Airlines Affected</strong>: All major carriers</li>
<li><strong>Significance</strong>: Widespread system-wide event affecting 60 destination airports. Only 48.3% of diversions went to SAN; remainder cascaded to other destinations indicating severe capacity constraints.</li>
</ul>
</section>
<section id="cluster-2-dallasfort-worth-dfw---regional-disruption" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="cluster-2-dallasfort-worth-dfw---regional-disruption"><span class="header-section-number">4.2</span> Cluster 2: Dallas/Fort Worth (DFW) - Regional Disruption</h3>
<ul>
<li><strong>Primary Destination</strong>: DFW (Dallas/Fort Worth International)</li>
<li><strong>Common Diversion</strong>: IAH (George Bush Intercontinental, Houston)</li>
<li><strong>Period</strong>: November 4-5, 2024</li>
<li><strong>Number of Events</strong>: 110 diversions to DFW; 186 system-wide</li>
<li><strong>Unique Origins</strong>: 89 airports (ATL, CLT, BOS most common)</li>
<li><strong>Airlines Affected</strong>: AA, UA, DL, WN (major carriers)</li>
<li><strong>Significance</strong>: Regional event with 59.1% of diversions to DFW. Texas-area concentrated pattern showing regional coordination among airports.</li>
</ul>
</section>
<section id="cluster-3-chicago-ohare-ord---regional-disruption" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="cluster-3-chicago-ohare-ord---regional-disruption"><span class="header-section-number">4.3</span> Cluster 3: Chicago O’Hare (ORD) - Regional Disruption</h3>
<ul>
<li><strong>Primary Destination</strong>: ORD (Chicago O’Hare International)</li>
<li><strong>Common Diversion</strong>: IND (Indianapolis International)</li>
<li><strong>Period</strong>: August 24-26, 2021</li>
<li><strong>Number of Events</strong>: 108 diversions to ORD; 187 system-wide</li>
<li><strong>Unique Origins</strong>: 87 airports (ORD, LAX, DFW, MSP most common)</li>
<li><strong>Airlines Affected</strong>: UA, AA, DL (major carriers at ORD)</li>
<li><strong>Significance</strong>: Regional Midwest event with 57.8% of diversions to ORD. Midwest corridor (IND, STL, MKE) used as overflow capacity.</li>
</ul>
<hr>
</section>
</section>
<section id="operational-implications" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="operational-implications"><span class="header-section-number">5</span> Operational Implications</h2>
<section id="for-airlines" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="for-airlines"><span class="header-section-number">5.1</span> For Airlines</h3>
<p><strong>Recommendation 1: Pre-Position Crews and Aircraft at Hub Diversion Airports</strong> - DEN, IAD, LAX consistently absorb diversions; position spare crews and aircraft there during high-risk periods - Example: During winter months (peak diversion season), AA should have crew standby at DEN and PHX based on SAN cluster patterns - Benefit: Reduces ground time and passenger delays by enabling immediate rebooking and crew swaps</p>
<p><strong>Recommendation 2: Implement Tiered Disruption Protocols Based on Event Scope</strong> - Train dispatch teams to identify system-wide vs.&nbsp;regional events within first 30 minutes - Regional events: Activate local recovery (reroute through nearby hubs like IAH, IND, STL) - System-wide events: Activate network-wide coordination with partner airlines - Benefit: Faster response, better passenger communication, reduced cascading delays</p>
<p><strong>Recommendation 3: Address American Airlines’ Elevated Diversion Rate</strong> - AA’s 27.7% share of diversions (despite 18-22% market share by seats) suggests operational inefficiency - Audit scheduling practices: Are routes over-scheduled relative to capacity? - Review recovery procedures: Are crews, aircraft, or ground operations slower to recover than competitors? - Benchmark against DL/UA best practices in disruption management - Benefit: Competitive advantage, lower costs, improved on-time performance</p>
<p><strong>Recommendation 4: Route Planning Accounts for Regional Vulnerability Patterns</strong> - DFW/ORD events show that some routes are inherently riskier (e.g., flights to SAN during winter) - Consider scheduling more flexible routing options or tighter buffers on historically problematic routes - Benefit: Fewer diversions, better customer retention, reduced operational costs</p>
</section>
<section id="for-airport-operations" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="for-airport-operations"><span class="header-section-number">5.2</span> For Airport Operations</h3>
<p><strong>Finding</strong>: Major airports (DEN, IAD, LAX, DFW, ORD) experience consistent overflow diversion traffic. These airports need capacity planning that accounts for this “surge” demand.</p>
<p><strong>Operational Needs</strong>: - Gate availability: These hub airports need flex-gate agreements for sudden diversions - Ground crew staffing: Surge staffing protocols during peak diversion periods - Coordination with airlines: Pre-positioned spare aircraft and crews need dedicated parking/handling facilities</p>
</section>
<section id="for-policy-makers" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="for-policy-makers"><span class="header-section-number">5.3</span> For Policy Makers</h3>
<p><strong>System-Level Insight</strong>: The U.S. aviation system shows clear capacity vulnerabilities. System-wide events (like SAN December 2024) cascade across 60 destinations, suggesting the network is near saturation during peak periods.</p>
<p><strong>Implication 1</strong>: Infrastructure investment should prioritize secondary airports that naturally absorb diversions (DEN, IAD, LAX) rather than adding capacity to already-congested hubs</p>
<p><strong>Implication 2</strong>: ATC coordination protocols between regional hubs (like Texas airports or Midwest corridor) can mitigate cascade effects during disruptions</p>
<hr>
</section>
</section>
<section id="statistical-confidence" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="statistical-confidence"><span class="header-section-number">6</span> Statistical Confidence</h2>
<section id="methodology-validation" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="methodology-validation"><span class="header-section-number">6.1</span> Methodology Validation</h3>
<p><strong>Data Quality</strong>: - 100% of records had complete geographic data for origin and diversion airports - 100% of records had valid airline information - No significant gaps in time period coverage (July 2021 - December 2024)</p>
<p><strong>Analysis Rigor</strong>: - Temporal clustering with 12-hour threshold validated against known disruption events - 64,815 total records analyzed - Geospatial analysis using standardized airport coordinates from FAA/OpenFlights databases</p>
<p><strong>Limitations on Confidence</strong>: - Weather data not available (cannot verify causation) - Only first diversion tracked (cascade effects underestimated) - Diversion reason not recorded in BTS data</p>
</section>
<section id="can-we-generalize-these-findings" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="can-we-generalize-these-findings"><span class="header-section-number">6.2</span> Can We Generalize These Findings?</h3>
<p><strong>Yes, for</strong>: - Identifying which airports experience most diversions - Understanding temporal clustering patterns - Ranking airlines by diversion frequency - Geographic clustering of diversion hubs</p>
<p><strong>Cautiously, for</strong>: - Predicting future diversions (patterns may change with schedule changes) - Determining causes of diversions - Quantifying exact passenger impact</p>
<p><strong>No, for</strong>: - Specific weather-related predictions - Mechanical failure analysis - International flight patterns</p>
<hr>
</section>
</section>
<section id="what-surprised-us" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="what-surprised-us"><span class="header-section-number">7</span> What Surprised Us</h2>
<p><strong>Surprise 1: American Airlines’ Diversion Disparity</strong> - Expected: Similar diversion rates for similarly-sized carriers (AA, UA, DL) - Found: AA diverts 29% more than DL despite comparable network size - Explanation: Could reflect AA’s more aggressive scheduling, different network vulnerabilities, or less efficient disruption recovery compared to competitors</p>
<p><strong>Surprise 2: System-Wide vs.&nbsp;Regional Event Distinction</strong> - Expected: Disruptions would affect multiple destinations equally - Found: Some events (SAN) cascade across 60 destinations; others (DFW, ORD) stay concentrated in regions - Explanation: Geographic location and airport connectivity determine how disruptions propagate—coastal/hub airports have more alternative routing options</p>
<p><strong>Surprise 3: Consistent Hub Diversion Pattern</strong> - Expected: Diversions would spread randomly across available airports - Found: Same 10 airports (DEN, IAD, LAX, DFW, etc.) consistently absorb diversions - Explanation: These airports have the capacity, geographic position, and service infrastructure that airlines naturally choose for diversions</p>
<hr>
</section>
<section id="what-this-reveals-about-aviation" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="what-this-reveals-about-aviation"><span class="header-section-number">8</span> What This Reveals About Aviation</h2>
<section id="the-bigger-picture" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="the-bigger-picture"><span class="header-section-number">8.1</span> The Bigger Picture</h3>
<p>This analysis reveals that the U.S. aviation system operates with <strong>predictable but exploitable vulnerabilities</strong>: - Diversion patterns cluster around specific airports and time periods - Regional networks (Texas hub, Midwest corridor) successfully coordinate to handle disruptions - Some airlines manage disruptions significantly better than others despite similar network sizes</p>
</section>
<section id="system-resilience" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="system-resilience"><span class="header-section-number">8.2</span> System Resilience</h3>
<p><strong>Positive</strong>: - Hub airports (DEN, IAD, LAX, DFW) successfully absorb diversions—the network has natural “safety valves” - Regional coordination shows airlines can work together effectively during disruptions - 50.6 average daily diversions represents only 0.1% of total U.S. flights, showing overall system stability</p>
<p><strong>Negative</strong>: - System-wide events (like SAN) cascade across 60+ destinations, indicating limited redundancy in some network paths - American Airlines’ high diversion rate suggests operational inefficiencies can cascade through the network - Average 278.8-minute arrival delay indicates diversions create significant downstream impacts</p>
</section>
<section id="passenger-experience-implications" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="passenger-experience-implications"><span class="header-section-number">8.3</span> Passenger Experience Implications</h3>
<p>For the 64,815 passengers affected by these diversions over 45 months: - Average delay impact: 278.8 minutes (4.6+ hours) - System-wide events: Potential for missed connections and multi-day disruptions - Regional events: Usually resolved within regional airport network with lower passenger impact</p>
<hr>
</section>
</section>
<section id="limitations-of-this-analysis" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="limitations-of-this-analysis"><span class="header-section-number">9</span> Limitations of This Analysis</h2>
<section id="data-limitations" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="data-limitations"><span class="header-section-number">9.1</span> Data Limitations</h3>
<ol type="1">
<li><strong>No Weather Context</strong>:
<ul>
<li>Cannot determine if diversions were weather-related</li>
<li>BTS data lacks concurrent weather conditions</li>
<li><em>Impact</em>: Cannot verify our assumptions about causation</li>
</ul></li>
<li><strong>Single Diversion Only</strong>:
<ul>
<li>BTS only records first diversion</li>
<li>Cascading diversions not tracked</li>
<li><em>Impact</em>: May underestimate true system disruption (278.8 min avg arrival delay suggests significant cascades)</li>
</ul></li>
<li><strong>No Diversion Reason</strong>:
<ul>
<li>Cannot distinguish: weather vs.&nbsp;mechanical vs.&nbsp;ATC</li>
<li><em>Impact</em>: Cannot identify root causes</li>
</ul></li>
<li><strong>U.S. Domestic Only</strong>:
<ul>
<li>International diversions excluded</li>
<li><em>Impact</em>: Incomplete picture of some carriers</li>
</ul></li>
</ol>
</section>
<section id="methodological-limitations" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="methodological-limitations"><span class="header-section-number">9.2</span> Methodological Limitations</h3>
<ol type="1">
<li><strong>Temporal Clustering</strong>:
<ul>
<li>Uses 12-hour threshold to group diversions</li>
<li>Assumes temporal proximity indicates same root cause</li>
<li><em>Mitigation</em>: Results validated against known airport disruption events</li>
</ul></li>
<li><strong>Geographic Clustering</strong>:
<ul>
<li>Assumes nearby airports are related</li>
<li>May miss causal relationships</li>
<li><em>Mitigation</em>: Geospatial visualizations show clear geographic patterns</li>
</ul></li>
<li><strong>Time Periods</strong>:
<ul>
<li>Dataset spans 45 months (July 2021 - December 2024)</li>
<li>Recent patterns (post-Dec 2024) not included</li>
<li><em>Impact</em>: Patterns may have shifted since dataset ends</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="future-research-directions" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="future-research-directions"><span class="header-section-number">10</span> Future Research Directions</h2>
<section id="short-term-easy-to-do" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="short-term-easy-to-do"><span class="header-section-number">10.1</span> Short Term (Easy to Do)</h3>
<ol type="1">
<li><strong>Add Weather Data</strong>
<ul>
<li>Join BTS diversions with NOAA weather data</li>
<li>Validate whether SAN, DFW, ORD events correlate with weather</li>
<li>Identify which airports are most weather-sensitive</li>
</ul></li>
<li><strong>Deep-Dive into American Airlines</strong>
<ul>
<li>Compare scheduling patterns (flights per gate, turnaround times) vs.&nbsp;UA and DL</li>
<li>Analyze crew scheduling efficiency</li>
<li>Identify which routes/airports drive AA’s elevated diversion rate</li>
</ul></li>
<li><strong>Track Cascading Effects</strong>
<ul>
<li>Follow individual flights through secondary diversions</li>
<li>Quantify passenger impact (missed connections)</li>
<li>Model cascade duration</li>
</ul></li>
</ol>
</section>
<section id="medium-term-more-work" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="medium-term-more-work"><span class="header-section-number">10.2</span> Medium Term (More Work)</h3>
<ol start="4" type="1">
<li><strong>Predictive Modeling</strong>
<ul>
<li>Use features (route, date, season, time-of-day) to predict diversion likelihood by airline</li>
<li>Create airline-specific risk profiles</li>
<li>Identify best/worst routes for each carrier</li>
</ul></li>
<li><strong>Network Analysis</strong>
<ul>
<li>Model aviation system as network graph</li>
<li>Identify critical airports and routes</li>
<li>Simulate impact of airport closures on diversion patterns</li>
</ul></li>
<li><strong>Economic Impact</strong>
<ul>
<li>Estimate costs of diversions to each airline (fuel, crew, ground services)</li>
<li>Calculate passenger costs (hotel, meals, time value)</li>
<li>Quantify why AA’s high diversion rate matters financially</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="reproducibility" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="reproducibility"><span class="header-section-number">11</span> Reproducibility</h2>
<p>This analysis can be reproduced by:</p>
<ol type="1">
<li><strong>Downloading Data</strong>:
<ul>
<li>Visit https://www.transtats.bts.gov/</li>
<li>Download OTMC-OTP monthly files (2021-07 to 2024-12)</li>
</ul></li>
<li><strong>Running Analysis</strong>:
<ul>
<li>Execute notebook to process raw data</li>
<li>Run temporal clustering to identify clusters</li>
<li>Generate visualizations with Plotly</li>
</ul></li>
<li><strong>Code Availability</strong>:
<ul>
<li>All analysis code provided in GitHub repository</li>
<li>Python environment specified in requirements.txt</li>
<li>Full documentation in README</li>
</ul></li>
</ol>
<hr>
</section>
<section id="conclusion" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">12</span> Conclusion</h2>
<p>Flight diversions in the U.S. aviation system are not random events but rather <strong>systematic patterns</strong> that cluster around specific airports during specific time periods. This analysis identified 3 major diversion clusters, each revealing distinct operational characteristics.</p>
<p>The findings suggest that:</p>
<ol type="1">
<li><p><strong>American Airlines operates with significantly higher diversion rates than competitors</strong> - This represents both a competitive disadvantage and an opportunity for operational improvement through benchmarking against Delta and United’s practices.</p></li>
<li><p><strong>Disruptions follow predictable geographic patterns</strong> - System-wide events cascade across 60+ destinations while regional events stay concentrated. Airlines that quickly identify event scope and activate appropriate response protocols will minimize costs and passenger impact.</p></li>
<li><p><strong>Hub airports naturally absorb diversions</strong> - DEN, IAD, LAX, DFW, and ORD serve as consistent “safety valves.” Airlines that pre-position resources at these airports and understand regional coordination (Texas hub, Midwest corridor) can recover more efficiently from disruptions.</p></li>
</ol>
<p>By understanding these patterns, airlines can: - <strong>American Airlines</strong>: Audit scheduling and recovery procedures to match UA/DL efficiency - <strong>All Airlines</strong>: Pre-position crews/aircraft at hub diversion airports during peak risk periods - <strong>Airports</strong>: Plan capacity expansion to support consistent diversion traffic - <strong>Industry</strong>: Improve network redundancy to reduce cascade effects during system-wide disruptions</p>
<p>This work demonstrates that publicly available transportation data, when combined with modern data science techniques, can reveal actionable insights into complex system behavior and competitive performance differences.</p>
<hr>
</section>
<section id="about-this-analysis" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="about-this-analysis"><span class="header-section-number">13</span> About This Analysis</h2>
<p><strong>Project Type</strong>: Data Science Final Project (MUSA 5500) <strong>Analysis Period</strong>: July 2021 - December 2024 <strong>Total Records</strong>: 64,815 flight diversions <strong>Methods</strong>: Temporal clustering (12-hour threshold), geospatial analysis, statistical analysis <strong>Technologies</strong>: Python, Pandas, NumPy, Plotly, Jupyter Notebook</p>
<p><strong>Author</strong>: Jun <strong>Date Completed</strong>: December 2024 <strong>Last Updated</strong>: December 12, 2025</p>
<hr>
<p><strong>Questions or Comments?</strong> This analysis is open for discussion and feedback. The patterns identified suggest areas for further investigation and practical application in aviation operations.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/your-github-username\.github\.io\/flight-diversions");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>